### ISSUE TITLE
Missing instructions in labs/Improvements

### ISSUE THREAD

**Issue by ReneSchumacher** [microsoft/everyonecancode#113]
During the session today (June 13, 2023), I noticed the following "issues" (will update this issue during the two days to capture all feedback):

## General
* Some of my attendees seemed to have closed the terminal window after challenge 1 and got stuck in challenge 2. *We should add a description on how to open a terminal window in VS Code if all terminals are closed*
* Some attendees had German as default language in their browsers, so all terms are different. *We should create a fully German version of the labs.*
* When logging into Azure, some attendees clicked `Next` when prompted to configure MFA (even though I told them not to do so 😆). Unfortunately, the account then seems to be blocked 😞. *We should put a note (maybe with an **important**) into the lab description, not to do so.*
* Feedback from one attendee: *please include agenda in invitation, so people who are not available for the whole day can plan better.*

## Challenge 2
* In the beginning, we give the branch name as `Update-title-and-color` (in the example) and later ask attendees to run the command `git checkout update-title-and-color`. Some attendees in my group created the branch with a capital U and, thus, the command failed because Git is case-sensitive. *We should change the same to use lower-case letters only.*
* The pull request flow has changed and must be updated.

## Challenge 3
* GitHub pages configuration site looks different. *We must update the screenshots.*
* Instructions tell attendees to create new app service plan instead of choosing the existing one. *We should change that.*
* In the check backend step, we describe "*Navigate to the Overview tab*", then "*Hit the URL*". However, both screenshots are wrong and there are multiple URLs in the app service overview. *We should update the screenshots (full overview for Web App, initial Swagger UI screenshot and an additional screenshot of the page after opening `/images`) and correctly write `click the URL shown as default domain`.*

## Challenge 5
* The secret names in the text and the screenshot are different. *We should update the screenshot to reflect the correct value.*
* Feedback from attendee: *Please give a little more information than just saying "as you did before".* 😉
* The screenshot at the bottom is wrong. *We should change and show the regular screen to trigger the workflow.*

**Comment by waeltken** [comment]
Thanks a lot for the detailed writeup!

**Comment by ReneSchumacher** [comment]
@waeltken I believe, this is the full feedback. After my vacation, I'm happy to help implement all mentioned improvements. In addition, I again received the feedback that we're not really teaching how to code. Maybe we can change the lab and focus more on coding and less on Azure services configuration?

**Comment by waeltken** [comment]
Closing as this relates to last year's rollout.
