### ISSUE TITLE
Final version of the lab 

### ISSUE THREAD

**Issue by lgmorand** [microsoft/everyonecancode#30]
Hello guys

we were told to use this repo for the AnyoneCanCode event in June. We plan to do a fork to translate it. But in order to manage version, it would be easier to have a finished version one.

Some challenges [seem in progress](https://github.com/microsoft/anyonecancode/blob/main/instructions/day2/Vision/README.md) and some screenshots are [in german](https://github.com/microsoft/anyonecancode/tree/main/instructions/day1/Application)

1- is the lab being considered as finished ?
2- if not, when ?
3- how can we help :) with my colleague @clemlesne we can give a boost

thanks

**Comment by clemlesne** [comment]
Would it be simpler to just for this and PR with a whole translation to English? Everyone around the earth would be able to use it then.

**Comment by lgmorand** [comment]
yes, helping having a full english version here first, and then, potentially translate it

**Comment by lrivallain** [comment]
Hi @lgmorand @clemlesne,
Will be happy to help in translation. 
Could a new set of localized README could be easier to maintain than a fork ?

**Comment by waeltken** [comment]
Closing as this relates to last years rollout.
